language: java

script:
  - mvn test
  - mvn install -DskipTests=true

jdk:
  - oraclejdk8

notifications:
  email: false

deploy:
  provider: heroku
  api_key: 117895aa-1ff3-4959-b82b-a5d207307c3c
  
