language: java
script:
- mvn test
- mvn install -DskipTests=true
jdk:
- oraclejdk8
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: KSqug3h5NprVh3RlsXug34lO4CZu3kktW1eQyteJgYVcLDTYbaS4xGHD5ZAnmMqeqF8005GkTBi+DK4Cl0bEyhvX3+G6gRzSxbIY6hDSA6UQ2NkYQNT/9GQsOx0P/EVheTh5GTHjgRISj1eWTS7sfRKGFycbJMqnzZpdKg/TU5yZX8u9vb9kh69aMGb+Q7y67R0ELISUFe+vPTGJbUmaKB+WwhJpaHhTl0m8aVYcTpORwlQeqH6M8WNQ1ny5rN8qwh8BMlPzlCzNuPZRwO3qDkzPn+7hyk2xoCAgQQq83zEJaVhui7hgmzXRX1nb0JoAyqewOrKssdCBGwMhQtx9HAtbz+OGjJAwhPv+/F22jB+0yx0hezEMOQlP21TAuuG0KxDkTKAmMTJ+Gsvb/y89i7QvuIg1JnZ2n6EFxurx22TXsvSa+938mgJoGLpAll01TrQxv+NDpC4AThl38LPVju8ht9f5gStKKt9kT1q2Gugkh6VsARDFgIs0WPX9W6D1mvdOqKA+W0ErRcMVKzw6jMloLcZE7e2Ulz4iScoMg/lror7AlE3ZjQsPfSMY7Lhd39vcNWIKkDgZYzFDo9X2sLS2oUw6Y2uk/AIaAW1UaGSt90KvrqAnYteVvlJ2w+x0QLQOHQMUiTEgiyhawjnIj/Uq1HhM0OVP0tutgO2b01w=
  app: koodi
  on:
    repo: kooditeam/koodi
    branch: master

