language: java

script:
  - mvn test -f koodi/pom.xml
  - mvn install -DskipTests=true -f koodi/pom.xml

jdk:
  - oraclejdk8
  - oraclejdk7

deploy:
  provider: heroku
  api_key: 117895aa-1ff3-4959-b82b-a5d207307c3c
  
